export var insightsFlushTopic = "insights.flush";
export var featureFlagEvaluatedTopic = "featureflag.evaluated.topic";
export var featureFlagEvaluatedBufferTopic = "featureflag.evaluated.buffer.topic";
export var websocketReconnectTopic = "network.websocket.reconnect";
export var debugModeQueryStr = "debugmode"; // will print debug logs if true
export var insightsTopic = "insights.topic";
export var devModeEventName = "fbdevmodechange";
export var devModeStorageKey = "fbdevmode";
export var devModeBtnId = "fb-devmode-btn";
//# sourceMappingURL=constants.js.map